# Generated by Django 6.1.1 on 2026-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=8, help_text='Retail $/gallon', max_digits=12)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geocode_source', models.CharField(choices=[('census', 'US Census Gazetteer (town centre)'), ('osm', 'OpenStreetMap Nominatim (town centre)')], max_length=10)),
                ('highways', models.CharField(blank=True, help_text='I-/US- highways named in the address, space separated', max_length=100)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
            },
        ),
    ]
